name: Build Spring Boot Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t todo-backend .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag todo-backend shaidurpranto/todo-backend:latest

      - name: Push Docker image
        run: docker push shaidurpranto/todo-backend:latest
